"""
Validates trading signals using Claude API (claude-sonnet-4-6).
Uses prompt caching for the system prompt to reduce API costs.
Only signals with rules confidence >= 6.0 are sent for validation.
"""

from __future__ import annotations

import json
import os
from typing import List, Optional

import anthropic
import yaml
from pathlib import Path

from agents.base_agent import BaseAgent
from agents.signal_agent import Signal

_SYSTEM_PROMPT = """You are an expert Indian stock market trading analyst specializing in NSE and BSE markets. Your role is to validate algorithmic trading signals generated by a rules-based system.

You must evaluate each signal considering:
1. Technical signal quality (already scored by rules engine)
2. Market context and current conditions
3. News and sentiment impact on the stock
4. Risk-reward appropriateness for Indian retail traders
5. SEBI compliance (paper trading only)

You will respond ONLY with a valid JSON object — no markdown, no extra text.

Response format:
{
  "verdict": "APPROVE" | "REJECT" | "MODIFY",
  "confidence": <float 0-10>,
  "reasoning": "<2-3 sentence plain English explanation>",
  "key_risks": ["<risk1>", "<risk2>"],
  "modified_stop_loss": <float or null>,
  "modified_target_2": <float or null>
}

Guidelines:
- APPROVE: Signal aligns with market context, risk is acceptable
- REJECT: Signal has flaws Claude detects that rules missed (bad news, overbought sector, macro risk)
- MODIFY: Signal is good but stop-loss or target should be adjusted
- Be decisive — avoid wishy-washy reasoning
- Consider Nifty 50 trend when evaluating individual stocks
- Flag if stock has upcoming earnings / results / board meeting that adds risk"""


class ClaudeValidationAgent(BaseAgent):
    def __init__(self):
        super().__init__("ClaudeAgent")
        cfg_path = Path(__file__).parent.parent / "config" / "trading_config.yaml"
        with open(cfg_path) as f:
            cfg = yaml.safe_load(f)
        self._model = cfg["claude"]["model"]
        self._max_tokens = cfg["claude"]["max_tokens"]
        self._min_confidence = cfg["signals"]["min_confidence_for_claude"]
        self._client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"), timeout=30.0)

    def run(self, signals: List[Signal], sentiment_context: Optional[dict] = None) -> List[Signal]:
        """Validate signals via Claude. Returns signals with updated status and confidence."""
        validated = []
        for signal in signals:
            if signal.confidence < self._min_confidence:
                signal.status = "REJECTED"
                signal.claude_verdict = "SKIP"
                signal.claude_reasoning = f"Confidence {signal.confidence} below threshold {self._min_confidence}"
                validated.append(signal)
                continue

            result = self._validate_signal(signal, sentiment_context or {})
            if result:
                signal.claude_verdict = result.get("verdict", "REJECT")
                signal.claude_reasoning = result.get("reasoning", "")
                adjusted_conf = result.get("confidence", signal.confidence)
                signal.confidence = round((signal.confidence + adjusted_conf) / 2, 1)

                if result.get("modified_stop_loss"):
                    signal.stop_loss = round(float(result["modified_stop_loss"]), 2)
                if result.get("modified_target_2"):
                    signal.target_2 = round(float(result["modified_target_2"]), 2)

                signal.status = "APPROVED" if signal.claude_verdict == "APPROVE" else "REJECTED"
            else:
                # API failure — fail safe: do not trade unvalidated signals
                signal.claude_verdict = "SKIP"
                signal.claude_reasoning = "Claude API unavailable — signal held for safety"
                signal.status = "REJECTED"

            validated.append(signal)
            self.log_info(
                f"{signal.symbol}: Claude={signal.claude_verdict} conf={signal.confidence}",
                symbol=signal.symbol
            )

        approved = sum(1 for s in validated if s.status == "APPROVED")
        self.log_info(f"Claude validated {len(validated)} signals: {approved} approved")
        return validated

    def _validate_signal(self, signal: Signal, sentiment: dict) -> Optional[dict]:
        news_context = ""
        sym_sentiment = sentiment.get(signal.symbol, {})
        if sym_sentiment:
            news_context = f"\nRecent news sentiment for {signal.symbol}: {sym_sentiment.get('sentiment', 'NEUTRAL')} — {sym_sentiment.get('headline', '')}"

        market_context = sentiment.get("_market", {})
        market_note = ""
        if market_context:
            market_note = f"\nNifty 50 trend: {market_context.get('trend', 'neutral')} | India VIX: {market_context.get('vix', 'unknown')}"

        user_message = f"""Validate this trading signal:

Symbol: {signal.symbol}
Type: {signal.signal_type}
Strategy: {signal.strategy} ({signal.timeframe})
Entry: ₹{signal.entry_price}
Stop Loss: ₹{signal.stop_loss} ({signal.sl_pct}% risk)
Target 1: ₹{signal.target_1}
Target 2: ₹{signal.target_2}
Risk-Reward: {signal.risk_reward}x
Rules Confidence: {signal.confidence}/10
Signal Reasons: {', '.join(signal.reasons)}
{market_note}{news_context}

Respond with JSON only."""

        try:
            response = self._client.messages.create(
                model=self._model,
                max_tokens=self._max_tokens,
                system=[
                    {
                        "type": "text",
                        "text": _SYSTEM_PROMPT,
                        "cache_control": {"type": "ephemeral"},  # Prompt caching
                    }
                ],
                messages=[{"role": "user", "content": user_message}],
            )
            raw = response.content[0].text.strip()
            return json.loads(raw)
        except json.JSONDecodeError:
            self.log_error(f"Claude returned invalid JSON for {signal.symbol}")
            return None
        except anthropic.APIError as e:
            self.log_error(f"Claude API error for {signal.symbol}: {e}")
            return None
        except Exception as e:
            self.log_error(f"Unexpected error for {signal.symbol}: {e}")
            return None
