"""
Validates trading signals using an AI model (Anthropic Claude or OpenAI GPT).
Provider is selected via config (validation.provider) or auto-detected from env keys.
Priority: Anthropic > OpenAI. Signals are REJECTED if no provider is available.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Dict, List, Optional

import yaml

from agents.base_agent import BaseAgent
from agents.signal_agent import Signal

_TUNING_STATE_PATH = Path(__file__).parent.parent / "data" / "tuning_state.json"

_SYSTEM_PROMPT = """You are an expert Indian stock market trading analyst specializing in NSE and BSE markets. Your role is to validate algorithmic trading signals generated by a rules-based system.

You must evaluate each signal considering:
1. Technical signal quality (already scored by rules engine)
2. Market context and current conditions
3. News and sentiment impact on the stock
4. Risk-reward appropriateness for Indian retail traders
5. SEBI compliance (paper trading only)

You will respond ONLY with a valid JSON object — no markdown, no extra text.

Response format:
{
  "verdict": "APPROVE" | "REJECT" | "MODIFY",
  "confidence": <float 0-10>,
  "reasoning": "<2-3 sentence plain English explanation>",
  "key_risks": ["<risk1>", "<risk2>"],
  "modified_stop_loss": <float or null>,
  "modified_target_2": <float or null>
}

Guidelines:
- APPROVE: Signal aligns with market context, risk is acceptable
- REJECT: Signal has flaws the rules engine missed (bad news, overbought sector, macro risk)
- MODIFY: Signal is good but stop-loss or target should be adjusted
- Be decisive — avoid wishy-washy reasoning
- Consider Nifty 50 trend when evaluating individual stocks
- Flag if stock has upcoming earnings / results / board meeting that adds risk"""


def _resolve_provider(preferred: str) -> str:
    """Return the provider to actually use based on config + available env keys."""
    has_anthropic = bool(os.environ.get("ANTHROPIC_API_KEY"))
    has_openai = bool(os.environ.get("OPENAI_API_KEY"))

    if preferred == "anthropic":
        return "anthropic" if has_anthropic else "none"
    if preferred == "openai":
        return "openai" if has_openai else "none"
    # auto: Anthropic first, OpenAI fallback
    if has_anthropic:
        return "anthropic"
    if has_openai:
        return "openai"
    return "none"


class ClaudeValidationAgent(BaseAgent):
    def __init__(self):
        super().__init__("ClaudeAgent")
        cfg_path = Path(__file__).parent.parent / "config" / "trading_config.yaml"
        with open(cfg_path) as f:
            cfg = yaml.safe_load(f)

        self._min_confidence = cfg["signals"]["min_confidence_for_claude"]
        self._modify_approval_threshold = cfg["signals"].get("min_confidence_to_trade", 7.0)
        self._max_tokens = cfg["claude"]["max_tokens"]

        preferred = cfg.get("validation", {}).get("provider", "auto")
        self._provider = _resolve_provider(preferred)
        self._threshold_overrides: Dict[str, float] = self._load_threshold_overrides()

        if self._provider == "anthropic":
            import anthropic as _anthropic
            self._model = cfg["claude"]["model"]
            self._client = _anthropic.Anthropic(
                api_key=os.environ.get("ANTHROPIC_API_KEY"), timeout=30.0
            )
            self.log_info("Validation provider: Anthropic Claude")

        elif self._provider == "openai":
            import openai as _openai
            self._model = cfg["openai"]["model"]
            self._client = _openai.OpenAI(
                api_key=os.environ.get("OPENAI_API_KEY"), timeout=30.0
            )
            self.log_info("Validation provider: OpenAI GPT")

        else:
            self._model = None
            self._client = None
            self.log_warning("No AI API key found — all signals will be REJECTED")

    def run(self, signals: List[Signal], sentiment_context: Optional[dict] = None,
            composite_ratings: Optional[dict] = None, perf_context: str = "") -> List[Signal]:
        """Validate signals via AI provider. Returns signals with updated status and confidence."""
        validated = []
        cr = composite_ratings or {}
        for signal in signals:
            threshold = self._threshold_overrides.get(signal.strategy, self._min_confidence)
            if signal.confidence < threshold:
                signal.status = "REJECTED"
                signal.claude_verdict = "SKIP"
                signal.claude_reasoning = f"Confidence {signal.confidence} below threshold {threshold}"
                validated.append(signal)
                continue

            result = self._validate_signal(signal, sentiment_context or {}, cr, perf_context)
            if result:
                signal.claude_verdict = result.get("verdict", "REJECT")
                signal.claude_reasoning = result.get("reasoning", "")
                adjusted_conf = result.get("confidence", signal.confidence)
                signal.confidence = round((signal.confidence + adjusted_conf) / 2, 1)

                if result.get("modified_stop_loss"):
                    signal.stop_loss = round(float(result["modified_stop_loss"]), 2)
                if result.get("modified_target_2"):
                    signal.target_2 = round(float(result["modified_target_2"]), 2)

                if signal.claude_verdict == "APPROVE":
                    signal.status = "APPROVED"
                elif (signal.claude_verdict == "MODIFY"
                      and signal.confidence >= self._modify_approval_threshold):
                    # Conditional approval: tighten stop 20% if AI didn't supply a specific SL
                    if not result.get("modified_stop_loss"):
                        sl_dist = signal.entry_price - signal.stop_loss
                        signal.stop_loss = round(signal.entry_price - sl_dist * 0.8, 2)
                    signal.claude_reasoning = (signal.claude_reasoning or "") + " [Conditional: tighter stop applied]"
                    signal.status = "APPROVED"
                else:
                    signal.status = "REJECTED"
            else:
                signal.claude_verdict = "SKIP"
                signal.claude_reasoning = "AI API unavailable — signal held for safety"
                signal.status = "REJECTED"

            validated.append(signal)
            self.log_info(
                f"{signal.symbol}: verdict={signal.claude_verdict} conf={signal.confidence}",
                symbol=signal.symbol
            )

        approved = sum(1 for s in validated if s.status == "APPROVED")
        self.log_info(f"Validated {len(validated)} signals via {self._provider}: {approved} approved")
        return validated

    def _validate_signal(self, signal: Signal, sentiment: dict, composite_ratings: dict,
                         perf_context: str = "") -> Optional[dict]:
        if self._provider == "none" or self._client is None:
            return None

        user_message = self._build_prompt(signal, sentiment, composite_ratings, perf_context)

        if self._provider == "anthropic":
            return self._call_anthropic(signal.symbol, user_message)
        return self._call_openai(signal.symbol, user_message)

    def _build_prompt(self, signal: Signal, sentiment: dict, composite_ratings: dict,
                      perf_context: str = "") -> str:
        sym_sentiment = sentiment.get(signal.symbol, {})
        news_context = ""
        if sym_sentiment:
            news_context = (
                f"\nRecent news sentiment for {signal.symbol}: "
                f"{sym_sentiment.get('sentiment', 'NEUTRAL')} — {sym_sentiment.get('headline', '')}"
            )

        market_context = sentiment.get("_market", {})
        market_note = ""
        if market_context:
            market_note = (
                f"\nNifty 50 trend: {market_context.get('trend', 'neutral')} "
                f"| India VIX: {market_context.get('vix', 'unknown')}"
            )

        composite_rating = composite_ratings.get(signal.symbol, "UNKNOWN")
        composite_note = f"\nIn-house composite TA rating: {composite_rating}" if composite_rating != "UNKNOWN" else ""

        perf_note = f"\nHistorical performance context: {perf_context}" if perf_context else ""

        return (
            f"Validate this trading signal:\n\n"
            f"Symbol: {signal.symbol}\n"
            f"Type: {signal.signal_type}\n"
            f"Strategy: {signal.strategy} ({signal.timeframe})\n"
            f"Entry: ₹{signal.entry_price}\n"
            f"Stop Loss: ₹{signal.stop_loss} ({signal.sl_pct}% risk)\n"
            f"Target 1: ₹{signal.target_1}\n"
            f"Target 2: ₹{signal.target_2}\n"
            f"Risk-Reward: {signal.risk_reward}x\n"
            f"Rules Confidence: {signal.confidence}/10\n"
            f"Signal Reasons: {', '.join(signal.reasons)}"
            f"{market_note}{news_context}{composite_note}{perf_note}\n\n"
            f"Respond with JSON only."
        )

    def _call_anthropic(self, symbol: str, user_message: str) -> Optional[dict]:
        import anthropic as _anthropic
        try:
            response = self._client.messages.create(
                model=self._model,
                max_tokens=self._max_tokens,
                system=[
                    {
                        "type": "text",
                        "text": _SYSTEM_PROMPT,
                        "cache_control": {"type": "ephemeral"},
                    }
                ],
                messages=[{"role": "user", "content": user_message}],
            )
            return json.loads(response.content[0].text.strip())
        except json.JSONDecodeError:
            self.log_error(f"Anthropic returned invalid JSON for {symbol}")
            return None
        except _anthropic.APIError as e:
            self.log_error(f"Anthropic API error for {symbol}: {e}")
            return None
        except Exception as e:
            self.log_error(f"Unexpected Anthropic error for {symbol}: {e}")
            return None

    def _load_threshold_overrides(self) -> Dict[str, float]:
        """Read per-strategy threshold overrides from tuning_state.json."""
        if not _TUNING_STATE_PATH.exists():
            return {}
        try:
            with open(_TUNING_STATE_PATH) as f:
                state = json.load(f)
            overrides = state.get("threshold_overrides", {})
            if overrides:
                self.log_info(f"Loaded threshold overrides: {overrides}")
            return {k: float(v) for k, v in overrides.items()}
        except Exception as e:
            self.log_error(f"Could not load threshold overrides: {e}")
            return {}

    def _call_openai(self, symbol: str, user_message: str) -> Optional[dict]:
        import openai as _openai
        try:
            response = self._client.chat.completions.create(
                model=self._model,
                max_tokens=self._max_tokens,
                temperature=0,
                response_format={"type": "json_object"},
                messages=[
                    {"role": "system", "content": _SYSTEM_PROMPT},
                    {"role": "user", "content": user_message},
                ],
            )
            return json.loads(response.choices[0].message.content.strip())
        except json.JSONDecodeError:
            self.log_error(f"OpenAI returned invalid JSON for {symbol}")
            return None
        except _openai.APIError as e:
            self.log_error(f"OpenAI API error for {symbol}: {e}")
            return None
        except Exception as e:
            self.log_error(f"Unexpected OpenAI error for {symbol}: {e}")
            return None
